#!/usr/bin/env bash
# Install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
FIRST_PATH="listen 80 default_server;"
FIRST_PATH_TWO="\trewrite /redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
SECOND_PATH="/etc/nginx/sites-available/default"
sudo sed -i "/$FIRST_PATH/a\\$FIRST_PATH_TWO" $SECOND_PATH
sudo service nginx restart
