#!/usr/bin/env bash
# This script is displaying "Best School" 10 times with while

IFS=:
cat < /etc/passwd |
while read -r f0 f1 f2 f3 f4 f5 f6
do
    echo "The user $f0 is part of the $f3 gang, lives in $f5 and rides $f6. $f2's place is protected by the passcode $f1, more info about the user here: $f4"
done
