#!/usr/bin/env bash
# script that configures an Ubuntu server with the below requirements
cp /etc/hosts ~/hosts.new
sed -i '/127.0.0.1/127.0.0.2   localhost/' ~/hosts.new
sed -i '/.[0-9]facebook.com/d' ~/hosts.new
sed -i '\$a8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
